start: 0
lock: 0
books:
  - book_name: 无限血核
    book_id: '1013607299'
    start: 3

  - book_name: 呢喃诗章
    book_id: '1027630529'
    start: 3

  - book_name: 三国请回答！崩坏的三国演义
    book_id: '1028755947'
    start: 3

  - book_name: 我的女友来自未来 (标记)
    book_id: '1025656512'

  - book_name: 我的治愈系游戏 (标记)
    book_id: '1025901449'

  - book_name: 洪荒历 (标记)
    book_id: '1011940368'
    start: 3 

  - book_name: 道诡异仙 (完结)
    book_id: '1031794030'
    start: 3

  - book_name: 星门 (完结)
    book_id: '1027669580'

  - book_name: 五百个郭靖 (完结)
    book_id: '1030653673'

  - book_name: 十方武圣 (完结)
    book_id: '1024088056'

  - book_name: 我的一天有48小时 (完结)
    book_id: '1013009467'

  - book_name: 这个人仙太过正经 (完结)
    book_id: '1021635590'
    
  - book_name: 舌尖上的霍格沃茨 (完结)
    book_id: '1013293257'
    
  - book_name: 我只想安静的做个苟道中人 (完结)
    book_id: '1026694115'
