name: Automatic Fetch Reviews

on:
  workflow_dispatch:
  schedule:
    - cron: "00 3,12,22 * * *"


env:
  DOWNSTREAM_BRANCH: master
  OUTPUT_PATH: ../output
  LOGS_PATH: ../logs
  CATEGORY_PATH: ../docs/category
  README_PATH: ../../../README.md
  TZ: Asia/Shanghai


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.DOWNSTREAM_BRANCH }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Clone repo
        run: |
          if [ -n "${{ secrets.ACCESS_TOKEN }}" ];then
          echo "Clone private repo"
          git clone https://oauth2:${{ secrets.ACCESS_TOKEN }}@github.com/${{github.repository}}.git
          else
          echo "Clone public repo"
          git clone https://github.com/${{github.repository}}.git
          fi


      - name: Install NPM dependencies
        run: cd $PWD/$(basename $PWD) && npm install

      - name: Run
        run: |
          cp config.yaml $PWD/$(basename $PWD)
          cd $PWD/$(basename $PWD)/src && node index

      - name: Set git identity
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"

      - name: Commit files
        run: |
          if [ -n "$(git status -s)" ];then
          git add .
          git commit -m "Update $(date "+%Y/%m/%d %H:%M")"
          else
          echo "There is no merge commits."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.DOWNSTREAM_BRANCH }}
