name: Automatic Fetch Reviews

on:
  workflow_dispatch:
  #push:
  #branches:
  #- dev
  schedule:
    - cron: "00 3,12,22 * * *"

env:
  GITHUB_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Switch branch
        run: |
          git fetch origin ${{ env.GITHUB_BRANCH }}
          git checkout ${{ env.GITHUB_BRANCH }}

      - name: Clone repo
        run: |
          if [ -n "${{ secrets.ACCESS_TOKEN }}" ];then
          echo "Clone private repo"
          git clone https://oauth2:${{ secrets.ACCESS_TOKEN }}@github.com/${{github.repository}}.git
          else
          echo "Clone public repo"
          git clone https://github.com/${{github.repository}}.git
          fi

      - name: Copy
        run: cp -rf $PWD/$(basename $PWD)/* $PWD

      - name: Install NPM dependencies
        run: npm install

      - name: Run
        run: node index

      - name: Commit files
        env:
          TZ: Asia/Shanghai
        run: |
          git config --local user.email "github-actions@noreply.github.com"
          git config --local user.name "github-actions"

          if [ -n "$(git status -s)" ];then
          git add .
          git commit -m "Update $(date "+%Y/%m/%d %H:%M")"
          else
          echo "There is no merge commits."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.GITHUB_BRANCH }}

      - name: Telegram push
        env:
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        if: ${{ env.TELEGRAM_TO != '' && env.TELEGRAM_TOKEN != '' }}
        run: node push.js ${{ github.event_name }}
