name: Test

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths-ignore:
      - .github/workflows
      - README.md

env:
  DOWNSTREAM_BRANCH: test
  OUTPUT_PATH: ../output
  LOGS_PATH: ../logs
  CATEGORY_PATH: ../docs/category
  README_PATH: ../../../README.md
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.DOWNSTREAM_BRANCH }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Clone repo
        run: |
          if [ -n "${{ secrets.ACCESS_TOKEN }}" ];then
          echo "Clone private repo"
          git clone https://oauth2:${{ secrets.ACCESS_TOKEN }}@github.com/${{github.repository}}.git
          else
          echo "Clone public repo"
          git clone https://github.com/${{github.repository}}.git
          fi


      - name: Install NPM dependencies
        run: cd $PWD/$(basename $PWD) && npm install

      - name: Run
        run: |
          cp config.yaml $PWD/$(basename $PWD)
          cd $PWD/$(basename $PWD)/src && node index

      - name: Setup GIT user
        uses: fregante/setup-git-user@v1

      - name: Commit files
        run: |
          if [ -n "$(git status -s)" ];then
          git add .
          git commit -m "Update $(date "+%Y/%m/%d %H:%M")"
          else
          echo "There is no merge commits."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.DOWNSTREAM_BRANCH }}
