name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  #schedule:
  #- cron: "00 3,12,22 * * *"

env:
  DOWNSTREAM_BRANCH: test
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.DOWNSTREAM_BRANCH }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Clone repo
        run: |
          if [ -n "${{ secrets.ACCESS_TOKEN }}" ];then
          echo "Clone private repo"
          git clone https://oauth2:${{ secrets.ACCESS_TOKEN }}@github.com/${{github.repository}}.git
          else
          echo "Clone public repo"
          git clone https://github.com/${{github.repository}}.git
          fi

      - name: Copy
        run: cp -rf $PWD/$(basename $PWD)/* $PWD

      - name: Install NPM dependencies
        run: npm install

      - name: Run
        run: cd src && node index

      - name: Set git identity
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"

      - name: Commit files
        run: |
          if [ -n "$(git status -s)" ];then
          git add .
          git commit -m "Update $(date "+%Y/%m/%d %H:%M")"
          else
          echo "There is no merge commits."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.DOWNSTREAM_BRANCH }}

      - name: Get latest Git commit hash
        run: |
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> ${GITHUB_ENV}

      - name: Send notify to telegram
        if: ${{ env.TELEGRAM_TO && env.TELEGRAM_TOKEN}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            本章说更新！---${{ github.event_name }}
            [View it On Github](${{ github.server_url }}/${{ github.repository }}/commit/${{env.COMMIT_HASH}})
            小说网站
            https://book.qidian.com/info/1029553244/#Catalog
        env:
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
